apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <YOUR_GIT_REPO_URL>
    targetRevision: qa
    path: environments/qa/k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
