name: Terragrunt Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (prod, stage, qa)'
        required: true
        default: 'prod'
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2

      - name: Install Terragrunt
        run: |
          TG_VERSION=v0.67.16
          wget https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64 \
            -O /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt
          terragrunt --version

      - name: Start Minikube
        run: |
          minikube start

      - name: Set KUBECONFIG for Minikube
        run: |
          export KUBECONFIG=$(minikube config view --format '{{.KubeConfigPath}}')
          echo "KUBECONFIG set to Minikube configuration"

      - name: Terragrunt ${{ github.event.inputs.action }}
        env:
          KUBECONFIG: $KUBECONFIG
        run: |
          cd kubernetes/argocd
          terragrunt ${{ github.event.inputs.action }} -auto-approve
