name: Terragrunt Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (prod, stage, qa)'
        required: true
        default: 'prod'
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Install Terragrunt v0.53.4
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.53.4/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Terragrunt ${{ github.event.inputs.action }}
        run: |
          cd kubernetes/argocd
          terragrunt ${{ github.event.inputs.action }} -auto-approve
