name: Terragrunt Deploy

on:
  push:
    branches:
      - main
      - prod
      - stage
      - qa

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.0/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Terragrunt Apply
        run: |
          cd kubernetes/argocd
          terragrunt apply -auto-approve
