name: Terragrunt Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (prod, stage, qa)'
        required: true
        default: 'prod'
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2

      - name: Install Terragrunt v0.61.7
        run: |
          curl -sL https://github.com/gruntwork-io/terragrunt/releases/download/v0.61.7/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt ${{ github.event.inputs.action }}
        run: |
          cd kubernetes/argocd
          terragrunt ${{ github.event.inputs.action }} -auto-approve
